// packages/andromeda-react-components/src/components/Button/Button.tsx
import React from "react";
import clsx from "clsx";
import styles from "./Button.module.css";

type ButtonProps = Readonly<{
  label: string;
  onClick: () => void;
  disabled?: boolean;
}>;

export const Button: React.FC<ButtonProps> = ({
  label,
  onClick,
  disabled = false,
}) => {
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={clsx(styles["Button"], {
        [styles["Button--disabled"]]: disabled,
      })}
    >
      {label}
    </button>
  );
};

// packages/andromeda-vue-components/src/components/Button/Button.vue
<script lang="ts" setup>
import clsx from "clsx";
import styles from "./Button.module.css";

defineProps<{
  type: "button" | "submit" | "reset";
  disabled: boolean;
  onClick: () => void;
}>();
</script>

<template>
  <button
    :class="
      clsx(styles['Button'], {
        [styles['Button--disabled']]: disabled,
      })
    "
    :type="type"
    :disabled="disabled"
    @click="onClick"
  >
    <slot />
  </button>
</template>
